# version: '3.8'

# services:
#   mongodb:
#     image: mongo:latest
#     container_name: mongodb_container
#     ports:
#       - "27017:27017"
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: admin
#       MONGO_INITDB_ROOT_PASSWORD: password
#     volumes:
#       - mongo_data:/data/db

# volumes:
#   mongo_data:


version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  backend:
    build: backend
    container_name: backend_container
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/grant_db
    ports:
      - "5000:5000"
    volumes:
      - .:/app

volumes:
  mongo_data:

networks:
  grant_network:
    driver: bridge